//const promise1 = new Promise((resolve, reject) => {
   //resolve("Veri Alımı Başarılı") ;
   //reject("Veri Alımı Başarısız");
//});
//console.log(promise1);

// promise1.then(value => {
//     console.log(value);
// }) then ile resolve veri yakalandı

// promise1.catch(error => {
//     console.log(error);
// }); hata catch metodu ile yakalandı